name = "JHD5t"
uuid = "2c627ec0-346f-4991-9b0b-d83cfb5d2b82"
version = "0.1.0"
authors = ["jjgomezcadenas <jjgomezcadenas@gmail.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"

[compat]
ArgParse = "1.2.0"
CSV = "0.10.15"
DataFrames = "1.7.0"
Glob = "1.3.1"
HDF5 = "0.17.2"
Interpolations = "0.16.1"
PhysicalConstants = "0.2.4"
Plots = "1.40.18"
Pluto = "0.20.19"
PlutoUI = "0.7.72"
Printf = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
StatsPlots = "0.15.8"
Test = "1.11.0"
Unitful = "1.24.0"
UnitfulEquivalences = "0.2.0"
